### ISSUE TITLE
Unable to find valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by aalfi** [jrieke/cnn-interpretability#2]
Hello!
I am trying to train your example model.
I am getting this error. Please let me know if you can help
Thank you

From small-dataset.ipynb

> trainer.fit_loader(train_loader,
            val_loader=val_loader,
            num_epoch=20, 
            verbose=1,
            cuda_device=cuda_device)

**Comment by derEitel** [comment]
Do you have a matching version of CUDA and cuDNN installed for your pytorch version?
Please see here:
https://pytorch.org/get-started/previous-versions/

**Comment by aalfi** [comment]
Thank you for your clarification!
