### ISSUE TITLE
Image paths

### ISSUE THREAD

**Issue by mariaupc** [jrieke/cnn-interpretability#3]
Good morning,

I am trying to reproduce your work running `interpretation-mri.ipynb`, with the images directly downloded from the ADNI webpage. Apparently, the current paths have changed, and some errors appear. Do you have an updated code that supports the new versions of the dataset and its new directory structure?

Thank you very much in advance for your time.

**Comment by derEitel** [comment]
Hi @mariaupc, have you processed the images and moved them into the folder structure as explained [here](https://github.com/jrieke/cnn-interpretability#images)?

**Comment by mariaupc** [comment]
Thank you, initially I thought the preprocessing steps were also included in the notebooks, that is why the directories structures did not apparently match.
